// Generated by CoffeeScript 1.8.0
(function() {
  var GoogleMap, extend;

  extend = require('extend');

  GoogleMap = (function() {
    "use strict";
    GoogleMap.prototype._defaults = {
      id: 'id',
      lalo: null,
      output: 'output',
      markerImage: ''
    };

    function GoogleMap(opts) {
      this.opts = extend({}, defaults, opts);
      this.events();
    }

    GoogleMap.prototype.initialize = function() {
      var customMapType, featureOpts, map, mapOptions, marker, styledMapOptions;
      featureOpts = [
        {
          'stylers': [
            {
              'hue': ''
            }
          ],
          'elementType': '',
          'featureType': ''
        }
      ];
      mapOptions = {
        zoom: 16,
        center: this.opts.lalo,
        zoomControl: false,
        scaleControl: false,
        panControl: false,
        streetViewControl: false,
        overviewMapControl: false,
        mapTypeControl: false
      };
      styledMapOptions = {
        name: this.opts.id
      };
      map = new google.maps.Map(document.getElementById(this.opts.output), mapOptions);
      marker = new google.maps.Marker({
        position: this.opts.lalo,
        map: map,
        icon: this.opts.markerImage
      });
      customMapType = new google.maps.StyledMapType(featureOpts, styledMapOptions);
      map.mapTypes.set(this.opts.id, customMapType);
      return this;
    };

    GoogleMap.prototype.events = function() {
      google.maps.event.addDomListener(window, 'load', (function(_this) {
        return function() {
          return _this.initialize();
        };
      })(this));
      return this;
    };

    return GoogleMap;

  })();

  if (typeof define === 'function' && define.amd) {
    define(function() {
      return GoogleMap;
    });
  } else if (typeof module !== 'undefined' && module.exports) {
    module.exports = GoogleMap;
  } else {
    window.GoogleMap || (window.GoogleMap = GoogleMap);
  }

}).call(this);
